### ISSUE TITLE
App Store Optimization

### ISSUE THREAD

**Issue by croaky** [thoughtbot/Tropos#108]
Short short, I think we should change:

* App Name to "Tropos - Local weather forecasts for humans"
* Keywords to sun, rain, snow, cloud, wind, local, sunny, high, low, cloudy, rainy, storm, tornado, hurricane, fahrenheit

Not sure whether this is a code change or iTunes Connect-only?

Details:

I did a little research into App Store Optimization for Tropos and its competitors using https://sensortower.com:

## Yahoo! Weather app

* Estimated to be worth $187 million.
* Ranked #2 in "Essentials-Weather" category.
* Ranked #7 in Top Free iPhone Apps.
* Won an Apple Design Award.
* A+ keyword optimization for weather, map, noaa, radar, best, sunset, sunrise, location, solar, watch, rain, snow, forecast, photo, storm, wind, sunny, hurricane

## Weather Channel

* Estimated to be worth $252 million.
* Ranked #1 in "Essentials"
* Ranked #1 in "Top Free iPhone Apps"
* B+ keyword optimization for map, radar, sunset, best, tornado, wach, snow, rain, forecast, local, storm, ski, wind, alert, severe, weather

## Weather Underground

* Estimated to be worth $25 million.
* Ranked #6 in Top Free iPhone Apps
* Ranked #16 in Top Grossing iPhone Apps - Weather
* Ranked #19 in Forecasts & Alerts

## Tropos

* Estimated to be worth $1,330
* Ranked #187 in Top Grossing iPhone Apps - Weather
* Ranked #115 in Top Paid iPhone Apps - Weather
* iPhone Rank of 926 for "forecast"
* iPhone Rank of 868 for "rain"
* iPhone Rank of 961 for "sun"
* iPhone Rank of 1,377 for "weather"
* iPhone Rank of 1,470 for "cloud"
* iPhone Rank of 519 for "wind"

## Analysis of Ranking Difficulty

I ran through a calculation to balance traffic, iPhone difficulty, and word length (we have a 100 letter limit in the Keywords field), and ranked by Traffic per Letter:

https://docs.google.com/a/thoughtbot.com/spreadsheets/d/1xVdWMrc7zUld0C6KG-…

Result:

* For what Tropos is and the ranked results, I think we want to ignore nws, noaa, tornado, storm, hurricane, temperature, thermometer, radar, etc.
* I think we want to include sun, rain, snow, local, cloud, wind, weather

## Some App Keyword Best Practices, Info

* Don't repeat keywords
* Don't use company or app name in keywords, these already discoverable
* Avoid keywords where you're not competitive
* App Name acts like keywords, but does not seem to be weighted more than actual keywords
* App Name is used to create app URL, which can help with Google 

## Current and Proposed App Name + Keywords

At https://itunes.apple.com/us/app/tropos-weather-forecasts-for/id955209376 

* App Name is "Tropos - Weather and forecasts for humans"
* Keywords are weather, forecast, forecasts, conditions, temperatures, high, low, wind, sunny, sun, cloudy, cloud, rainy, rain

The next time we update the app, I'm proposing we update to:

* App Name changed to "Tropos - Local weather forecasts for humans"
* Keywords changed to sun, rain, snow, cloud, wind, local, sunny, high, low, cloudy, rainy, storm, tornado,  hurricane, fahrenheit

**Comment by jakecraige** [comment]
Thanks! Updates made in the 1.1 release that's in beta review now.

**Comment by croaky** [comment]
Nice, 1.1 got released, too?
