### ISSUE TITLE
Improve offline state

### ISSUE THREAD

**Issue by tysongach** [thoughtbot/Tropos#116]
I’d love see a friendlier message when the device has no cell service or wifi. The current “Update Failed” message makes it seem like the app is at fault, rather than the fact that you have no connection.

A message along the lines of “You’re currently offline” would be more clear.

![2015-05-17 22 38 51](https://cloud.githubusercontent.com/assets/903327/7775879/dd5b7dd8-0084-11e5-9892-ba0394d236e7.png)

**Comment by jakecraige** [comment]
Tracking in Trello https://github.com/thoughtbot/Tropos/issues/116
