### ISSUE TITLE
Consider using CocoaPods-Keys

### ISSUE THREAD

**Issue by ashfurrow** [thoughtbot/Tropos#125]
We faced similar problems keeping keys secret when open sourcing our app [Eidolon](https://github.com/artsy/eidolon), so @orta made [CocoaPods-Keys](https://github.com/orta/cocoapods-keys), a CocoaPods plugin designed specifically for the use case you have here.

If you'd like to see what using CocoaPods-Keys instead of Secrets.h would look like, I'd be happy to send a pull request.

**Comment by Euraldius** [comment]
Thanks for the recommendation! I'd love to see what this looks like in a PR

**Comment by ashfurrow** [comment]
Cool! I'll send one tonight.
