### ISSUE TITLE
TRWeatherLocation is unused. 

### ISSUE THREAD

**Issue by tomkowz** [thoughtbot/Tropos#136]
I started rewriting classes from /Model directory to Swift and see that `TRWeatherLocation` is unused. Is there any purpose that this file is still listed in project instead of being deleted? Don't know if should move it to Swift or just delete it.

**Comment by jakecraige** [comment]
If it's not being used then please remove it. It must have been accidentally left around awhile ago.

**Comment by tomkowz** [comment]
Great, will do.

**Comment by tomkowz** [comment]
I would like to close the issue because it is fully handled by #137.
