### ISSUE TITLE
MVVM Architecture Question 

### ISSUE THREAD

**Issue by pnicholls** [thoughtbot/Tropos#138]
Hey folks, 

Thanks for open sourcing the project! Its great to watch the ThoughtBot team (and now others) doing what they do best.

My question is around `MVVM Architecture`, other implementations of MVVM seem to throw everything into the `viewModel` where Tropos has a controller object that seems to do most of the heavy lifting. What is the thinking around this? How do you decide where the responsibility of the controller & viewModel starts and ends?

To use an example, lets say Tropos one day requires user authentication in order to see the weather updates, this introduces a `authenticationViewController`, `authenticationController` and `authenticationViewModel`. 

If the `authenticated` state is determined by presence of a `accessToken` in `userDefaults` is it the controller that would be providing a RAC signal here? Is the viewModel aware of the authenticated state?

Thanks again!

**Comment by jakecraige** [comment]
I'm fairly new to this specific architecture myself so I'm not fully equipped to handle it so I'll let someone else :)

cc @thoughtbot/ios @hyperspacemark

**Comment by tomkowz** [comment]
+1

**Comment by tonyd256** [comment]
The point of moving to a more `MVVM Architecture` was to help with abstraction and organization but also to unit test as much of the app as possible. We've tried to look at Views as `UIView` and `UIViewController` subclasses. The code we put into these classes should be as minimal as possible. Ideally, they should request what they need from the Controller or ViewModel and immediately update the display.

So then it's the Controller's job to handle any logic needed. Maybe network requests, calculations, etc. It also holds onto the data Models needed for the View. The Controller should contain no View specific code so it could be reusable for similar Views.

The ViewModel is kind of a transformer of the data Model to what the View needs to display. For instance, you might want to display an address in the View but the data Model contains different properties for the different address fields. It's the ViewModel's job to use those Model properties and format a String for the View to display.

Sometimes you can think of the ViewModel as a short lived object. The View needs to update its display, so it asks its Controller for the ViewModel. The Controller instantiates the ViewModel with the data Model it has and returns it to the View. The View then updates the display using the ViewModel and discards it when it's finished.

The whole point is to move as much code and logic out from anything View specific. This makes that code much easier to unit test. It can also lead to reusable Controllers and ViewModels.

**Comment by jakecraige** [comment]
To answer how things would be set up for your example @pnicholls, you would likely have `AuthenticationViewController`, `AuthenticationController` and `Authentication`(Model). 

If you wanted an `authenticated` signal, the `AuthenticationController` would provide it. It would get it's value from `Authentication`. That class would handle pulling it from `NSUserDefaults`. 

One way to think about how we are viewing view models is by treating them as facades/presenters. [Facade Pattern](https://en.wikipedia.org/wiki/Facade_pattern). They should generally be pretty simple.

**Comment by pnicholls** [comment]
Thank you for the brilliant responses @jakecraige and @tonyd256, after reading your responses and looking at the code again it does seem like a really great pattern. :+1: 

One last question, lets say another feature is introduced that allows a user to tap an individual daily forecast to get more information but we want to pass along some data from the `weatherController`. How would you pass that data onto the new controller? 

In a more vanilla `MVVM` design the new viewController (individual daily forecast information) would be initialised with a viewModel provided by the weatherViewModel, would you do the same thing but pass controllers around instead of viewModels?

**Comment by TosinAF** [comment]
Had a quick question relating to this. When working with tableviewcells, Currently for every needed property, I create a public method on the view model, and i set the content of the cell using those public api's.

With a lot of properties, this can get quite long. Is it still preferred over doing something like cell configure with model object?

I ask because this has bothering me for some time now.

*Sorry if this is slyly off topic* *I can delete if so*
