### ISSUE TITLE
Fix CI

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Tropos#152]
Circle is broken, we should look at going back to Travis.

**Comment by DarthMike** [comment]
@gfontenot I've used [bitrise](https://www.bitrise.io/) before and it works very well.

**Comment by jakecraige** [comment]
It's pretty much all broken... Have you had a better experience with travis?

**Comment by gfontenot** [comment]
Nope. Everything is horrible.

**Comment by gfontenot** [comment]
@DarthMike Bitrise looks interesting, but as with most iOS specific solutions, does much more than we actually want. We just want a CI server that can run tests on PRs.

**Comment by jakecraige** [comment]
This is such a pain. Who wants to build a custom CI service? Anyone?? Anyone??

**Comment by jakecraige** [comment]
We could probably re-evaluate Circle now that it seems to be doing better and they have Carthage pre-installed and what not.

**Comment by sharplet** [comment]
> Circle is broken

What specifically is broken?

**Comment by gfontenot** [comment]
could have been any number of things. My bet is it was Xcode version issues. Should probably be fine now though.

**Comment by sharplet** [comment]
Closing this for now.
