### ISSUE TITLE
Not receiving push notifications

### ISSUE THREAD

**Issue by cpytel** [thoughtbot/Tropos#175]
On the latest beta, I've still not received any push notifications at all.

**Comment by klaaspieter** [comment]
Have you launched the latest beta after updating? It needs to resubscribe to Courier in order for push notifications to work. 

I've been receiving them (albeit in the wrong time zone).

**Comment by klaaspieter** [comment]
@gfontenot I remember you were testing this as well? Did you receive anything after updating?

**Comment by cpytel** [comment]
I updated the app and opened it.

What I'll do next is delete the app and reinstall it.

**Comment by klaaspieter** [comment]
I just realized you've changed time zones Chad. There is an issue where Tropos doesn't unsubscribe you from the old time zone. Can you check if you receive a notification at 9am in your previous time zone?

Tropos should still register you for your new time zone as well, but I've been having issues with that.

**Comment by cpytel** [comment]
I've not received any push notifications even when I was in my usual time zone.

**Comment by gfontenot** [comment]
I got a notification on Tuesday after updating, but haven't received one since.

**Comment by jakecraige** [comment]
I haven't received any even after initially updating. I just uninstalled and reinstalled, now I'll wait to see if I get one in ~20mins. I'll update after.

**Comment by jakecraige** [comment]
I got it! 

> It's hotter today than yesterday.

**Comment by jakecraige** [comment]
It seems I only got it the first day, haven't received one since

**Comment by klaaspieter** [comment]
Thanks @jakecraige and @gfontenot. I've been seeing the same. My current assumption is that it has something to do with silent notifications. 

The way I implemented is that Tropos web sends a silent (`content-available: 1`) notification. That _should_ wake up the app so that it can schedule a local notification. It appears that after the app has gone into the background either the app isn't woken up, or it doesn't actually present the location notification to the user.

I really like this approach because currently the server doesn't have to know anything about forecast.io or the client logic to change the forecast into a human readable string. Unfortunately I might have to change the approach and just have the server send a non-silent notification.

**Comment by klaaspieter** [comment]
I'm making some progress here #178. It appears there is an issue updating the weather forecast when the app is launched in response to a silent notification. Because the update errors, the local notification is never scheduled.

**Comment by klaaspieter** [comment]
Potential fix is available in latest beta. The best way to test if it's working now is:

1. Delete the current Tropos beta
2. Install the new Tropos beta
3. Open the Tropos beta
4. Use your phone as normal, but don't open Tropos again
5. Don't switch time zones

If the issue was fixed you should consistently receive a push notification around 9am in your time zone.

**Comment by klaaspieter** [comment]
Forget to add one step. Reboot your phone after opening Tropos. This should put the app in suspended state, which is the state that was causing issues.

**Comment by gfontenot** [comment]
Followed those instructions this morning and did not receive a push notification today.

**Comment by cpytel** [comment]
Me neither.

> On Jun 1, 2016, at 12:02 PM, Gordon Fontenot <notifications@github.com> wrote:
> 
> Followed those instructions this morning and did not receive a push notification today.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <https://github.com/thoughtbot/Tropos/issues/175#issuecomment-223040821>, or mute the thread <https://github.com/notifications/unsubscribe/AAATl1VmSmPGr6_7QC_WHWNsLKQs1mOPks5qHa0UgaJpZM4IoLsE>.
> 

---
Chad Pytel, Founder and CEO
617-482-1300 x113
http://thoughtbot.com 
http://twitter.com/thoughtbot

**Comment by klaaspieter** [comment]
I was seeing the same problem, until I generated a new provisioning profile. No clue why that worked.

I've been changing my phone's time zone to be able to test this more than once a day, if you want to participate here is a list of time zones by UTC offset:

```
[{:"-39600"=>"American Samoa"},
 {:"-36000"=>"Hawaii"},
 {:"-32400"=>"Alaska"},
 {:"-28800"=>"Pacific Time (US & Canada)"},
 {:"-25200"=>"Arizona"},
 {:"-21600"=>"Central America"},
 {:"-18000"=>"Bogota"},
 {:"-14400"=>"Atlantic Time (Canada)"},
 {:"-10800"=>"Brasilia"},
 {:"-7200"=>"Mid-Atlantic"},
 {:"-3600"=>"Azores"},
 {:"0"=>"Casablanca"},
 {:"3600"=>"Amsterdam"},
 {:"7200"=>"Athens"},
 {:"10800"=>"Baghdad"},
 {:"14400"=>"Abu Dhabi"},
 {:"18000"=>"Ekaterinburg"},
 {:"21600"=>"Almaty"},
 {:"25200"=>"Bangkok"},
 {:"28800"=>"Beijing"},
 {:"32400"=>"Osaka"},
 {:"36000"=>"Brisbane"},
 {:"39600"=>"Magadan"},
 {:"43200"=>"Auckland"},
 {:"46800"=>"Nuku'alofa"}]
```

Another option is to use the [logic used] by Tropos. Call it like `SendBroadcast.new.time_zones_where_it_is("08:42")`. Replacing the minutes with whatever minute it currently is. So if it's 17:30 your time, use the string 8:30.

[logic used]: https://github.com/thoughtbot/Tropos-Web/blob/master/lib/send_broadcast.rb#L18-L27

For this to work you have to go to Settings -> General -> Date & Time . Disable “Set Automatically” and select a time zone where it'll be 9am next. After changing the time zone, double tap the home button and swipe Tropos up. After that re-open Tropos and it'll register in the new time zone.

**Comment by cpytel** [comment]
I received the push notification this morning. I did happen to be using my phone actively (it wasn't locked) when it happened.

**Comment by jakecraige** [comment]
Huh, I didn't receive one this morning

**Comment by cpytel** [comment]
I received another one this morning at 9am on both my watch and phone and I was not actively using either and haven't launched Tropos since the new beta came out.

**Comment by jakecraige** [comment]
Huh, I reinstalled last night, did open it then and I think this morning, didn't receive one today

**Comment by jakecraige** [comment]
So this happened this morning 😂 Was someone doing some testing or something? 

![img_0942](https://cloud.githubusercontent.com/assets/3799709/15806806/cafd692e-2b00-11e6-9443-28d00330213b.PNG)

**Comment by klaaspieter** [comment]
I was not doing any testing. I'll see if I can find what happened. Considering everyone seems to be receiving push notifications I'm going to close this issue and move your issue into a new one #181.
