### ISSUE TITLE
Title of push notifications

### ISSUE THREAD

**Issue by cpytel** [thoughtbot/Tropos#180]
I was just going to post my image of this, thanks fully Jake provided an image for me:

![https://cloud.githubusercontent.com/assets/3799709/15806806/cafd692e-2b00-11e6-9443-28d00330213b.PNG]

You can see in Jake's image that the name on the push notification is `TodayWeatherForecast`.

There are a few things wrong with this, it's not "Today's", and there are no spaces.

But can we change this day "Tropos" instead?

**Comment by klaaspieter** [comment]
Yep, noticed this too. I believe this is localization gone wrong. It's trying to look up the localized text by the `TodayWeatherForecast` key, not finding any and just falling back to displaying the key instead.

> But can we change this day "Tropos" instead?

Are you saying you want it to just say “Tropos” as the title?

**Comment by klaaspieter** [comment]
Fixed by #183.
