### ISSUE TITLE
Receiving too many push notifications

### ISSUE THREAD

**Issue by klaaspieter** [thoughtbot/Tropos#181]
After not receiving any push notification @jakecraige now received too many notifications. 

[![Push notification galore](https://cloud.githubusercontent.com/assets/3799709/15806806/cafd692e-2b00-11e6-9443-28d00330213b.PNG)](https://github.com/thoughtbot/Tropos/issues/175#issuecomment-223652258)

**Comment by klaaspieter** [comment]
@jyurek is seeing the same thing:
> I’ve been getting notifications every few minutes for the past few hours.

![image](https://cloud.githubusercontent.com/assets/98880/15845348/d125800c-2ca4-11e6-81fb-b06ee8c13bc5.png)

**Comment by klaaspieter** [comment]
Jake's time zone is set to Cupertino. If I manually set my phone to the same time zone, `[NSTimeZone localTimeZone].name` returns `US/Pacific`. 

This is important because Tropos registers with a Courier channel using the parameterized name of the time zone. In other words if the time zone name is `US/Pacific` Tropos registers with the `us-pacific` Courier channel. 

I'm surprised Jake is receiving any notifications at all because these are the channels currently registered with Courier:

```ruby
["asia-dhaka",
 "asia-kolkata",
 "america-chicago",
 "america-los_angeles",
 "asia-hong_kong",
 "asia-yerevan",
 "europe-stockholm",
 "america-new_york",
 "asia-taipei",
 "europe-london"]
```

Furthermore I wasn't able to find a time where the Tropos backend ever broadcasts to the `us-pacific` channel. See #185 for more information.

**Comment by klaaspieter** [comment]
@jakecraige to better diagnose this issue would you mind running the attached app on your phone?

[timezone.zip](https://github.com/thoughtbot/Tropos/files/302016/timezone.zip)

**Comment by klaaspieter** [comment]
I released a new beta that has more logging. 

To view the logs open Xcode and go to “Window” -> “Devices”. Select your device and click the triangle in the bottom left of the window.

Please do the following after opening the logs:

1. Double tap the home button and swipe Tropos up.
2. Launch Tropos
3. Copy & Paste the contents of the log window

Also if this happens again, please capture the log as well.

**Comment by jakecraige** [comment]
@klaaspieter Would you like me to try that one or use the beta?

**Comment by klaaspieter** [comment]
@jakecraige The beta has more logging now making it possible to more easily see what's going on. If you're seeing this issue again I would love to know what the logs are saying.

The timezone.zip is a seperate app. It just shows what the system is reporting as your time zone. If you have the time I would love to see what it's showing for you.

**Comment by jakecraige** [comment]
👍  here you go
![img_0945](https://cloud.githubusercontent.com/assets/3799709/15901605/c4238b7e-2d58-11e6-9431-f5d800875896.PNG)

**Comment by klaaspieter** [comment]
Thank you, that explains why you are getting the notification and tells me where to look for debug information.

When I manually set my phone to San Francisco or Cupertino time zone it reports the name as “US Pacific”. The backend never broadcasts to a time zone called US Pacific, which is why I was surprised you were getting anything at all.

The backend _does_ broadcast to “America/Los_Angeles”, but I'm only seeing one broadcast every day.

Has this happened since the first time?

**Comment by jakecraige** [comment]
No, seems to only have happened that day.

**Comment by sharplet** [comment]
We've decided to back out push notifications functionality for now (#204).
