### ISSUE TITLE
Possible to be subscribe to multiple channels

### ISSUE THREAD

**Issue by klaaspieter** [thoughtbot/Tropos#188]
The [unsubscribe logic](https://github.com/thoughtbot/Tropos/blob/kp-release/Tropos/Sources/Controllers/TRApplicationController.m#L86-L90) doesn't handle failure. If unsubscribing fails that device will not likely ever be unsubscribed. This means that device will continue receiving push notification for a previous time zone.

A potential fix, that doesn't require complicated retry logic, is to keep a list of time zones to unsubscribe from in `NSUserDefaults` and on every app launch attempt to unsubscribe again.

**Comment by klaaspieter** [comment]
I'm also wondering if there is a RAC solution to the retry problem? @sharplet?

**Comment by sharplet** [comment]
The short answer is yes, RAC does have good support for retry logic. The basics:

- Objective-C:
    - [`-retry:`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Objective-C/RACSignal%2BOperations.h#L629-L633)
    - Or the more general [`-catch:`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Objective-C/RACSignal%2BOperations.h#L377-L378)
- Swift:
    - [`retry(_:)`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Swift/SignalProducer.swift#L1319-L1331)
    - Or the more general [`flatMapError(_:)`](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/5cfcdccdcc693e7d685b4f7b7cf2c2ccf5c59c8d/ReactiveCocoa/Swift/Flatten.swift#L927-L930)

I've used `retry` and `catch` in the past to implement an exponential backoff strategy.

**Comment by sharplet** [comment]
We've decided to back out push notifications functionality for now (#204).
