### ISSUE TITLE
Can't Build

### ISSUE THREAD

**Issue by ishall1** [thoughtbot/Tropos#216]
in LocationController+Bridging.swift

import CoreLocation
import ReactiveObjCBridge
import ReactiveSwift
import Result

it says no such module

**Comment by sharplet** [comment]
Hi! Could you please provide more information: what version of Xcode / macOS? Did you run [the `bin/setup` script](https://github.com/thoughtbot/Tropos/blob/master/bin/setup) first?

**Comment by sharplet** [comment]
I’m going to close this for now, but feel free to reopen if this is still an issue.

**Comment by ishall1** [comment]
> I’m going to close this for now, but feel free to reopen if this is still an issue.

i used pod to intergrate. but when i build the target, it says "No such module 'ReactiveObjCBridge'". thanks

**Comment by sharplet** [comment]
Could you try again on the latest master? I’ve just recently finished removing CocoaPods from the project (#224). (Also, make sure that Tropos.xcworkspace is deleted, as the project now only uses Tropos.xcodeproj.)

**Comment by ishall1** [comment]
> Could you try again on the latest master? I’ve just recently finished removing CocoaPods from the project (#224). (Also, make sure that Tropos.xcworkspace is deleted, as the project now only uses Tropos.xcodeproj.)
i tried on the latest master and it worked. thanks a lot!
